# Generated by Django 4.1.3 on 2022-12-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollingStation', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('registerdVoters', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('rejectedObj', models.IntegerField()),
                ('disputed', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('jofle', models.IntegerField()),
                ('osman', models.IntegerField()),
                ('major', models.IntegerField()),
                ('suleiman', models.IntegerField()),
            ],
        ),
    ]
