# Generated by Django 4.1.3 on 2022-12-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('pollingAgent', 'Polling Agent'), ('chiefAgent', 'Chief Agent')], default='Polling Agent', max_length=50),
        ),
    ]
