# Generated by Django 4.1.3 on 2022-12-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ward',
            field=models.CharField(choices=[('galbet', 'GALBET'), ('waberi', 'WABERI'), ('iftin', 'IFTIN'), ('township', 'TOWNSHIP')], max_length=50),
        ),
    ]
