# Generated by Django 4.1.3 on 2022-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vote_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='sender_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
