# Generated by Django 4.1.3 on 2022-12-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_suleiman_vote_feisal_vote_malow_vote_muhiadin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preliminary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100)),
                ('pollingStation', models.CharField(max_length=100)),
                ('stream', models.IntegerField()),
                ('osman', models.IntegerField()),
                ('dolal', models.IntegerField()),
                ('dekow', models.IntegerField()),
                ('malow', models.IntegerField()),
                ('feisal', models.IntegerField()),
            ],
        ),
    ]
