# Generated by Django 4.1.3 on 2022-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_preliminary'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminary',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
